### ISSUE TITLE
Лишнее прокси и обработка ошибок в скрипт для скачивания Qtranslate

### ISSUE THREAD

**Issue by carloscondit** [Solbreen/PSscripts#3]
1. Если прокси пригодился в одном скрипте, то это не значит что его нужно использовать во всех веб-запросах. В данном случае запрос идет на сервера google и он вряд ли будет ограничивать доступ к своим ресурсам.

2. Нужно добавить обработку ошибок как минимум в блок для скачивания файла и при создании временного каталога.

**Comment by Solbreen** [comment]
Готово!
